#!/usr/bin/env python3
"""
One-time fixture generator for ai-engine-runtime tests.

Produces a tiny Llama-3-style model and a reference forward-pass result
that the Rust implementation must match within tolerance.

Run once; commit the outputs. NOT a runtime/build dependency.

Requirements (one-time, in a Python venv):
    pip install torch==2.4 transformers==4.45 safetensors==0.4 tokenizers==0.20

Usage:
    cd crates/ai-engine-runtime
    python scripts/generate_toy_fixture.py

Output:
    fixtures/toy-llama-3/
"""

import json
import struct
from pathlib import Path

import torch
from safetensors.torch import save_model
from tokenizers import Tokenizer
from tokenizers.models import BPE
from tokenizers.pre_tokenizers import ByteLevel
from tokenizers.decoders import ByteLevel as ByteLevelDecoder
from tokenizers.trainers import BpeTrainer
from transformers import LlamaConfig, LlamaForCausalLM

OUT = Path(__file__).resolve().parent.parent / "fixtures" / "toy-llama-3"
OUT.mkdir(parents=True, exist_ok=True)

torch.manual_seed(20260523)

cfg = LlamaConfig(
    hidden_size=256,
    intermediate_size=512,
    num_hidden_layers=4,
    num_attention_heads=4,
    num_key_value_heads=2,
    vocab_size=512,
    max_position_embeddings=128,
    rope_theta=10000.0,
    rms_norm_eps=1e-5,
    tie_word_embeddings=True,
    torch_dtype="bfloat16",
)
cfg.architectures = ["LlamaForCausalLM"]

with open(OUT / "config.json", "w") as f:
    json.dump(cfg.to_dict(), f, indent=2)

model = LlamaForCausalLM(cfg).to(torch.bfloat16)
model.train(False)  # inference mode (no dropout)

save_model(model, str(OUT / "model.safetensors"))

tok = Tokenizer(BPE(unk_token="<unk>"))
tok.pre_tokenizer = ByteLevel(add_prefix_space=False)
tok.decoder = ByteLevelDecoder()
trainer = BpeTrainer(vocab_size=512, special_tokens=["<unk>"], min_frequency=1)
training_text = [
    "The quick brown fox jumps over the lazy dog.",
    "Hello, world! Foo bar baz.",
    "ai-engine runtime test fixture.",
    "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789",
]
tok.train_from_iterator(training_text, trainer)
tok.save(str(OUT / "tokenizer.json"))

prompt = "The quick brown fox"
(OUT / "reference_prompt.txt").write_text(prompt)

ids = tok.encode(prompt).ids
input_ids = torch.tensor([ids], dtype=torch.long)

with torch.no_grad():
    out = model(input_ids=input_ids, use_cache=False)

# Logits at final position, cast to f32 for reference precision.
logits = out.logits[0, -1, :].to(torch.float32)
arr = logits.numpy().tobytes(order="C")

with open(OUT / "reference_logits.bin", "wb") as f:
    f.write(arr)

(OUT / "README.md").write_text(
"""# toy-llama-3 fixture

Generated by `scripts/generate_toy_fixture.py`. Do not edit by hand.

| File | Purpose |
|---|---|
| config.json | HF-format model config (4 layers, hidden 256, GQA 4->2, vocab 512) |
| model.safetensors | bf16 weights, seeded so regeneration is bit-identical |
| tokenizer.json | minimal byte-level BPE, 512 vocab |
| reference_prompt.txt | the input prompt used to compute reference_logits.bin |
| reference_logits.bin | raw little-endian f32 logits at the FINAL token position, length=vocab_size |

The Rust forward pass must produce logits matching `reference_logits.bin`
within `max |a - b| < 1e-3` when run on the same prompt against the same
safetensors. This is the bytes-tolerant correctness gate.
""")

print(f"wrote fixtures to {OUT}")
print(f"  prompt token ids: {ids}")
print(f"  vocab_size: {cfg.vocab_size}")
print(f"  reference_logits first 4 values: {logits[:4].tolist()}")
