#!/usr/bin/env python3
"""
Generate the toy-llama-3-q8 fixture from the existing toy-llama-3 (bf16).

For each Linear weight in the bf16 fixture:
    scale = max(|weight|) / 127
    packed = clamp(round(weight / scale), -127, 127).astype(int8)
    write `<name>` as int8 with original shape
    write `<name>.scale` as a single-f32 scalar

Non-Linear tensors (embedding, layernorms, biases if any) stay as bf16.

The reference_prompt.txt, tokenizer.json, and reference_logits.bin are copied
unchanged from the bf16 fixture — Q8 output must match bf16 reference within
the tolerance asserted in tests/quant_reference_logits.rs.

Run once; commit outputs.
"""

import json
import shutil
import struct
from pathlib import Path

import numpy as np
import torch
from safetensors.torch import load_file, save_file

SRC = Path(__file__).resolve().parent.parent / "fixtures" / "toy-llama-3"
OUT = Path(__file__).resolve().parent.parent / "fixtures" / "toy-llama-3-q8"
OUT.mkdir(parents=True, exist_ok=True)

# Tensors to quantize: any Linear weight in the model.
# In Llama-3 / LlamaForCausalLM these are:
LINEAR_PATTERNS = [
    "self_attn.q_proj.weight",
    "self_attn.k_proj.weight",
    "self_attn.v_proj.weight",
    "self_attn.o_proj.weight",
    "mlp.gate_proj.weight",
    "mlp.up_proj.weight",
    "mlp.down_proj.weight",
    "lm_head.weight",   # tied with embedding — we still quantize the lm_head copy if separately stored
]

def should_quantize(name: str) -> bool:
    return any(p in name for p in LINEAR_PATTERNS)

# Load the bf16 weights.
src_tensors = load_file(SRC / "model.safetensors")
out_tensors = {}

for name, t in src_tensors.items():
    if should_quantize(name):
        # Cast to f32 for precise scale computation.
        w_f32 = t.to(torch.float32)
        max_abs = w_f32.abs().max().item()
        scale = max_abs / 127.0 if max_abs > 0 else 1.0
        packed = (w_f32 / scale).round().clamp(-127, 127).to(torch.int8)
        out_tensors[name] = packed
        # Scale companion: shape [1] for safetensors compatibility (rank-0 not allowed by spec).
        out_tensors[f"{name}.scale"] = torch.tensor([scale], dtype=torch.float32)
    else:
        # Pass through as-is.
        out_tensors[name] = t

save_file(out_tensors, OUT / "model.safetensors")

# Copy config + tokenizer + reference unchanged.
for fname in ["config.json", "tokenizer.json", "reference_prompt.txt", "reference_logits.bin"]:
    shutil.copy(SRC / fname, OUT / fname)

# Updated README.
(OUT / "README.md").write_text(
"""# toy-llama-3-q8 fixture

Generated by `scripts/generate_q8_fixture.py` from `toy-llama-3`. Do not edit by hand.

| File | Purpose |
|---|---|
| config.json | Same as toy-llama-3 (architecture identical) |
| model.safetensors | Q8 weights for Linear layers + f32 scale companions; non-Linear tensors are bf16 passthrough |
| tokenizer.json | Same as toy-llama-3 |
| reference_prompt.txt | Same as toy-llama-3 |
| reference_logits.bin | Same as toy-llama-3 — Q8 forward must match within ~1e-2 |

The Rust Q8 forward pass must produce logits matching `reference_logits.bin`
within `max |a - b| < 1e-2` when run on the same prompt against the same
checkpoint. Tolerance is looser than the bf16 gate (1e-3) because Q8
quantization introduces per-tensor rounding error of ~4e-3 per Linear op,
which accumulates over 4 layers + lm_head.
""")

print(f"Wrote Q8 fixture to {OUT}")

# Sanity print
total_orig = sum(t.numel() * t.element_size() for t in src_tensors.values())
total_q8 = sum(t.numel() * t.element_size() for t in out_tensors.values())
print(f"bf16 fixture size: {total_orig} bytes")
print(f"Q8   fixture size: {total_q8} bytes")
print(f"compression ratio: {total_orig / total_q8:.2f}x")
