#!/usr/bin/env python3
"""
Generate toy-llama-3-q4 from toy-llama-3 (bf16). Per-group symmetric Q4
(group size 32 along input dim). Pre-transposed: weights stored in math
order [in, out] (not HF's [out, in]).

Naming convention:
  <linear_name>.q4_weight       packed nibbles, shape [in, out/2], dtype uint8
  <linear_name>.q4_scale        per-(group, out_channel) scales, shape [in/32, out], dtype float32
  <other tensors>               unchanged (bf16 passthrough)

Run once; commit outputs.
"""

import json
import shutil
from pathlib import Path

import numpy as np
import torch
from safetensors.torch import load_file, save_file

SRC = Path(__file__).resolve().parent.parent / "fixtures" / "toy-llama-3"
OUT = Path(__file__).resolve().parent.parent / "fixtures" / "toy-llama-3-q4"
OUT.mkdir(parents=True, exist_ok=True)

GROUP_SIZE = 32

LINEAR_PATTERNS = [
    "self_attn.q_proj.weight",
    "self_attn.k_proj.weight",
    "self_attn.v_proj.weight",
    "self_attn.o_proj.weight",
    "mlp.gate_proj.weight",
    "mlp.up_proj.weight",
    "mlp.down_proj.weight",
    "lm_head.weight",
]

def should_quantize(name: str) -> bool:
    return any(p in name for p in LINEAR_PATTERNS)

def quantize_q4(w_f32: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor]:
    """
    w_f32: [out, in] (HF natural layout).
    Returns: (packed: uint8 [in, out/2], scales: float32 [in/32, out]).
    Pre-transposes to math order [in, out] internally.
    """
    out_dim, in_dim = w_f32.shape
    assert in_dim % GROUP_SIZE == 0, f"in dim {in_dim} not divisible by {GROUP_SIZE}"
    assert out_dim % 2 == 0, f"out dim {out_dim} must be even"

    # Transpose to math order [in, out].
    w = w_f32.transpose(0, 1).contiguous().float().numpy()  # [in, out]

    num_groups = in_dim // GROUP_SIZE
    # scales[g, j] = max(|w[g*32:(g+1)*32, j]|) / 7
    scales = np.zeros((num_groups, out_dim), dtype=np.float32)
    for g in range(num_groups):
        block = np.abs(w[g * GROUP_SIZE:(g + 1) * GROUP_SIZE, :])
        max_abs = block.max(axis=0)             # per-column max within this group
        # Avoid zero division; fall back to scale=1.0 for all-zero groups.
        scales[g, :] = np.where(max_abs > 0, max_abs / 7.0, 1.0)

    # Pack nibbles row-major. packed[i, j/2] holds col j (low nibble) and col j+1 (high nibble).
    packed = np.zeros((in_dim, out_dim // 2), dtype=np.uint8)
    for i in range(in_dim):
        g = i // GROUP_SIZE
        for j in range(0, out_dim, 2):
            s_lo = scales[g, j]
            s_hi = scales[g, j + 1]
            q_lo = int(np.clip(np.round(w[i, j] / s_lo), -7, 7))
            q_hi = int(np.clip(np.round(w[i, j + 1] / s_hi), -7, 7))
            nibble_lo = q_lo & 0x0F
            nibble_hi = q_hi & 0x0F
            packed[i, j // 2] = nibble_lo | (nibble_hi << 4)

    return torch.from_numpy(packed), torch.from_numpy(scales)

src_tensors = load_file(SRC / "model.safetensors")
out_tensors = {}

for name, t in src_tensors.items():
    if should_quantize(name):
        packed, scales = quantize_q4(t)
        out_tensors[f"{name}.q4_weight"] = packed
        out_tensors[f"{name}.q4_scale"] = scales
    else:
        out_tensors[name] = t

save_file(out_tensors, OUT / "model.safetensors")

# Copy config + tokenizer + reference unchanged.
for fname in ["config.json", "tokenizer.json", "reference_prompt.txt", "reference_logits.bin"]:
    shutil.copy(SRC / fname, OUT / fname)

(OUT / "README.md").write_text(
"""# toy-llama-3-q4 fixture

Generated by `scripts/generate_q4_fixture.py` from `toy-llama-3`. Do not edit by hand.

Per-group symmetric Q4 quantization (group size 32 along input dim).

| File | Purpose |
|---|---|
| config.json | Same as toy-llama-3 (architecture identical) |
| model.safetensors | Q4 packed weights + f32 scales; non-Linear tensors are bf16 passthrough |
| tokenizer.json | Same as toy-llama-3 |
| reference_prompt.txt | Same as toy-llama-3 |
| reference_logits.bin | Same as toy-llama-3 — Q4 forward must match within ~5e-2 |

Naming convention:
  `<linear_name>.q4_weight`  packed nibbles, uint8, shape `[in, out/2]`, pre-transposed
  `<linear_name>.q4_scale`   per-group scales, f32, shape `[in/32, out]`

The Rust Q4 forward pass must produce logits matching `reference_logits.bin`
within `max |a - b| < 5e-2` when run on the same prompt against the same
checkpoint. Tolerance is looser than Q8's (3e-2) because Q4 per-group
quantization is intrinsically less precise.
""")

bf16_size = sum(t.numel() * t.element_size() for t in src_tensors.values())
q4_size = sum(t.numel() * t.element_size() for t in out_tensors.values())
print(f"wrote Q4 fixture to {OUT}")
print(f"bf16 fixture: {bf16_size} bytes")
print(f"Q4   fixture: {q4_size} bytes")
print(f"compression ratio: {bf16_size / q4_size:.2f}x")
